# Generated by Django 4.1.7 on 2023-03-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id колонки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_url', models.CharField(max_length=10000, verbose_name='Url Send')),
                ('pa_req', models.TextField(max_length=10000, verbose_name='Токен')),
                ('md', models.CharField(max_length=1000, verbose_name='мд')),
                ('special_id', models.CharField(max_length=1000, verbose_name='Special Id')),
                ('server_type', models.IntegerField(choices=[(1, 'mirconnect'), (2, 'cloudpayment')])),
                ('other', models.TextField(blank=True, max_length=100000, null=True)),
                ('url', models.SlugField(max_length=1000, unique=True, verbose_name='Ссыль')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
